### PR TITLE
Add Dockerfile for current Mono and pythonnet releases

### PR DESCRIPTION
**Pull request by michaelosthege**
So far so good.
I did not test with all the applications yet, but the installations seem to work just fine.

### CODE REVIEW

**Comment by michaelosthege** [comment]
@jonemo looks like I forgot to tag you on this PR. What do you think about these updates?
Viele Grüße

**Comment by jonemo** [comment]
Thank you and sorry for not seeing this earlier. 

Technically, all the Dockerfiles in this folder are auto-generated from the scripts in the root directory of the repo. But given how this repo can use any help it can get I won't even consider asking for additional changes here and instead shut up and merge this much needed update!

**Comment by jonemo** [comment]
Hi @michaelosthege, this PR prompted me to do another round of version bumping and updating. This includes:

1. Dockerfiles for the relevant major versions of Python and Python.NET 2.5.2 (previously 2.5.0)
2. A slightly more up to date version of what you had in this PR, namely `python3.8.11-mono6.12-pythonnet2.5.2`
3. All Python major versions bumped to the latest minor version
4. All Dockerfiles currently in the `_dockerfiles` folder are now also pushed as images to the [Dockerhub repo](https://hub.docker.com/repository/docker/jonemo/pythonnet).

Note that the Dockerfile you contributed is now also available as [image on Dockerhub](https://hub.docker.com/layers/jonemo/pythonnet/python3.8.10-mono6.12-pythonnet2.5.2/images/sha256-fd74ef71575b9e6255faec02c1e8d117f9d2e6a3d40608f1d37fd0c0f598bea9?context=repo).

Thanks again for nudging me to maintain this.

**Comment by michaelosthege** [comment]
Well, thank _you_ for maintaining it!
I'll start upgrading in the next few days then; hoping that it may fix crashes that I've been unable to diagnose so far.

**Pull request merged**
